title: Flores RheoX Lab
description: Rheology, soft matter, surfactants, and multiscale simulations
url: https://floresrheoxlab.github.io

theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - research.md
  - people.md
  - publications.md
  - contact.md
