title: RheoX Lab
description: Rheology Across Scales @ UoM
url: https://floresrheoxlab.github.io

theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - research.md
  - people.md
  - publications.md
  - contact.md
